name: socialmedia
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  ionicons: ^0.2.2
  provider: ^6.1.1
  loading_overlay: ^0.3.0
  google_fonts: ^6.1.0
  cloud_firestore: ^4.14.0
  timeago: ^3.6.1
  cached_network_image: ^3.3.1
  flutter_chat_bubble: ^2.0.2
  animations: ^2.0.11
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  story: ^1.1.0
  like_button: ^2.0.5
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  uuid: ^4.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
  